# Generated by Django 3.1.1 on 2020-09-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=30)),
                ('parent_it', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdb_be.category')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('solution', models.TextField()),
                ('carrier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdb_be.carrier')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kdb_be.category')),
            ],
        ),
    ]
