# Generated by Django 3.1.1 on 2020-09-27 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kdb_be', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_it',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kdb_be.category'),
        ),
    ]
