# Generated by Django 3.1.1 on 2020-09-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kdb_be', '0003_auto_20200927_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_it',
            new_name='parent_id',
        ),
    ]
