# Generated by Django 3.1.1 on 2020-09-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kdb_be', '0004_auto_20200927_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceva_set', to='kdb_be.category'),
        ),
    ]
