# Generated by Django 3.1.1 on 2020-09-27 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kdb_be', '0006_auto_20200927_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
