# Generated by Django 3.1.1 on 2020-09-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdb_be', '0008_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S'),
        ),
    ]
