# Generated by Django 3.1.1 on 2020-09-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdb_be', '0010_auto_20200929_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='%Y-%m-%d %H:%M:%S'),
        ),
    ]
