# Generated by Django 3.1.1 on 2020-09-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='title',
            new_name='name',
        ),
    ]
